spring.application.name=ADC
server.port=8081

# Configuração alternativa com Windows Authentication
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=divulgai_db;encrypt=false;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configurações do JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true